# Generated by Django 6.0.2 on 2026-02-22 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('critical', 'Kritiek'), ('warning', 'Waarschuwing'), ('ok', 'Alles OK')], default='ok', max_length=10)),
                ('total_dependencies', models.IntegerField(default=0)),
                ('outdated_count', models.IntegerField(default=0)),
                ('vulnerability_count', models.IntegerField(default=0)),
                ('action_required', models.BooleanField(default=False)),
                ('tip_of_the_week', models.TextField(blank=True, default='')),
                ('quote_of_the_week', models.TextField(blank=True, default='')),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Kritiek'), ('warning', 'Waarschuwing'), ('info', 'Informatie')], max_length=10)),
                ('category', models.CharField(choices=[('security', 'Security Vulnerability'), ('api_deprecation', 'API Deprecation'), ('breaking_change', 'Breaking Change'), ('outdated', 'Verouderd Package')], max_length=20)),
                ('package_name', models.CharField(max_length=200)),
                ('current_version', models.CharField(blank=True, default='', max_length=50)),
                ('latest_version', models.CharField(blank=True, default='', max_length=50)),
                ('summary', models.TextField()),
                ('action_steps', models.TextField(blank=True, default='')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='dashboard.report')),
            ],
            options={
                'ordering': ['severity', 'package_name'],
            },
        ),
    ]
