# Generated by Django 6.0.2 on 2026-02-22 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Wachten'), ('running', 'Bezig...'), ('completed', 'Afgerond'), ('failed', 'Mislukt')], default='pending', max_length=10)),
                ('progress_message', models.CharField(default='Scan starten...', max_length=300)),
                ('error_message', models.TextField(blank=True, default='')),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
