# Generated by Django 6.0.2 on 2026-02-22 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_scanjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('start', 'Start'), ('agent', 'Agent actief'), ('tool', 'Tool aangeroepen'), ('thought', 'Agent denkt'), ('task_done', 'Taak afgerond'), ('result', 'Resultaat'), ('error', 'Fout'), ('info', 'Info')], default='info', max_length=15)),
                ('agent_name', models.CharField(blank=True, default='', max_length=100)),
                ('message', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.scanjob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
