# Generated by Django 6.0.2 on 2026-02-22 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_add_scanlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='job_type',
            field=models.CharField(choices=[('dependency', 'Dependency Monitor'), ('fiscal', 'Bedrijfsmonitor')], default='dependency', max_length=15),
        ),
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('intro', models.TextField(help_text='Korte, pakkende samenvatting (2-3 zinnen)')),
                ('body', models.TextField(help_text='Artikel inhoud in markdown')),
                ('category', models.CharField(choices=[('btw', 'BTW'), ('ib', 'Inkomstenbelasting'), ('vpb', 'Vennootschapsbelasting'), ('loonbelasting', 'Loonbelasting'), ('subsidies', 'Subsidies'), ('deadlines', 'Deadlines'), ('algemeen', 'Algemeen')], default='algemeen', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Concept'), ('published', 'Gepubliceerd'), ('archived', 'Gearchiveerd')], default='draft', max_length=10)),
                ('sources', models.JSONField(blank=True, default=list, help_text='Bron-URLs')),
                ('quality_score', models.IntegerField(default=5, help_text='Kwaliteitsscore 1-10 van reviewer-agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_tokens', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('scan_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='dashboard.scanjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
