# Generated by Django 6.0.2 on 2026-02-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_add_fiscal_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='active_agent',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='tasks_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='token_count',
            field=models.IntegerField(default=0),
        ),
    ]
