# Generated by Django 6.0.2 on 2026-02-22 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_add_scanjob_progress_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('process', models.CharField(choices=[('sequential', 'Sequential'), ('hierarchical', 'Hierarchical')], default='sequential', max_length=15)),
                ('verbose', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='scanjob',
            name='run_variables',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='job_type',
            field=models.CharField(choices=[('dependency', 'Dependency Monitor'), ('fiscal', 'Bedrijfsmonitor'), ('custom', 'Custom Team')], default='dependency', max_length=15),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='dashboard.team'),
        ),
        migrations.CreateModel(
            name='TeamAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(max_length=200)),
                ('goal', models.TextField()),
                ('backstory', models.TextField(blank=True, default='')),
                ('llm_provider', models.CharField(choices=[('gemini', 'Gemini'), ('anthropic', 'Anthropic'), ('openai', 'OpenAI')], default='gemini', max_length=20)),
                ('llm_model', models.CharField(default='gemini-3-flash-preview', max_length=100)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('max_iter', models.PositiveIntegerField(default=25)),
                ('verbose', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='dashboard.team')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('expected_output', models.TextField(blank=True, default='')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dashboard.teamagent')),
                ('context_tasks', models.ManyToManyField(blank=True, related_name='downstream_tasks', to='dashboard.teamtask')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dashboard.team')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('file_path', 'File path')], default='text', max_length=10)),
                ('default_value', models.TextField(blank=True, default='')),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='dashboard.team')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('team', 'name')},
            },
        ),
    ]
