# Generated by Django 6.0.2 on 2026-02-24 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_add_article_structured_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanjob',
            name='job_type',
            field=models.CharField(choices=[('dependency', 'Dependency Monitor'), ('fiscal', 'Bedrijfsmonitor'), ('custom', 'Custom Team'), ('compliance', 'WWFT Compliance')], default='dependency', max_length=15),
        ),
        migrations.CreateModel(
            name='ComplianceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('wettelijke_basis', 'Wettelijke basis'), ('clientenonderzoek', 'Cliëntenonderzoek'), ('risicobeleid', 'Risicobeleid kantoorniveau'), ('pep_sancties', 'PEP, sancties en herkomst middelen'), ('verscherpt_onderzoek', 'Verscherpt cliëntenonderzoek'), ('meldplicht', 'Meldplicht en transactiemonitoring'), ('herbeoordeling', 'Periodieke herbeoordeling'), ('compliance_infra', 'Intern compliance-infrastructuur'), ('bft_bevindingen', 'BFT inspectie-bevindingen'), ('actuele_wetgeving', 'Actuele wet- en regelgeving')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('ai_sources', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('default', 'Standaard'), ('checking', 'Wordt gecontroleerd'), ('updated', 'Bijgewerkt door AI'), ('error', 'Fout bij update')], default='default', max_length=10)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('can_ai_update', models.BooleanField(default=True)),
                ('office_action_required', models.BooleanField(default=False)),
                ('office_action_description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_check_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.scanjob')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
