# Generated by Django 6.0.2 on 2026-03-16 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_add_compliance_section_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(blank=True, default='', max_length=300, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('google_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('google_reviews_count', models.IntegerField(default=0)),
                ('business_type', models.CharField(blank=True, default='', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('new', 'Nieuw'), ('contacted', 'Benaderd'), ('interested', 'Geïnteresseerd'), ('not_interested', 'Geen interesse'), ('client', 'Klant')], default='new', max_length=20)),
                ('contact_channel', models.CharField(blank=True, choices=[('', '—'), ('linkedin', 'LinkedIn'), ('phone', 'Telefoon'), ('email', 'E-mail'), ('post', 'Post'), ('visit', 'Bezoek'), ('paid_ads', 'Betaalde reclame'), ('other', 'Anders')], default='', max_length=20)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='prospects', to='dashboard.prospectgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacesSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=300)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('radius_km', models.IntegerField(default=10)),
                ('business_type', models.CharField(blank=True, default='', max_length=100)),
                ('results_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.prospectgroup')),
            ],
            options={
                'verbose_name_plural': 'Places searches',
                'ordering': ['-created_at'],
            },
        ),
    ]
