# Generated by Django 6.0.2 on 2026-03-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_prospectgroup_prospect_placessearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('goals', models.TextField(blank=True, default='')),
                ('results', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('prospects_contacted', models.IntegerField(default=0)),
                ('prospects_interested', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sales diary entries',
                'ordering': ['-date'],
            },
        ),
    ]
