# Generated by Django 6.0.2 on 2026-03-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_seed_response_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_type', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('new', 'Nieuw'), ('not_contacted', 'Niet benaderd'), ('contacted', 'Benaderd'), ('interested', 'Geïnteresseerd'), ('not_interested', 'Geen interesse'), ('client', 'Klant')], default='new', max_length=20),
        ),
    ]
