# Generated by Django 6.0.2 on 2026-03-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_seed_business_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
