# Generated by Django 6.0.2 on 2026-03-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_prospect_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectresponse',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
