# Generated by Django 6.0.2 on 2026-03-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_templatecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='place_id',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddConstraint(
            model_name='prospect',
            constraint=models.UniqueConstraint(condition=models.Q(('place_id', ''), _negated=True), fields=('place_id',), name='unique_place_id_when_set'),
        ),
    ]
