# Generated by Django 6.0.2 on 2026-03-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_diarygoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsetemplate',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
