# Generated by Django 6.0.2 on 2026-03-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_responsetemplate_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
