# Generated by Django 6.0.2 on 2026-03-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_prospect_contact_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='prospect',
            name='contact_first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prospect',
            name='contact_last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
