# Generated by Django 6.0.2 on 2026-03-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_responsetemplate_is_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='aanhef',
            field=models.CharField(blank=True, choices=[('', '—'), ('Geachte heer', 'Geachte heer'), ('Geachte mevrouw', 'Geachte mevrouw'), ('Beste', 'Beste')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='prospect',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='contact_channel',
            field=models.CharField(blank=True, choices=[('', '—'), ('linkedin', 'LinkedIn'), ('phone', 'Telefoon'), ('email', 'E-mail'), ('contact_form', 'Contactformulier'), ('post', 'Post'), ('visit', 'Bezoek'), ('paid_ads', 'Betaalde reclame'), ('other', 'Anders')], default='', max_length=20),
        ),
    ]
