# Generated by Django 6.0.2 on 2026-03-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_seed_klant_template_and_update_kantoor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='website',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
