# Generated by Django 6.0.2 on 2026-03-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_seed_kantoor_demo_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='aanhef',
            field=models.CharField(blank=True, choices=[('', '—'), ('Geachte heer', 'Geachte heer'), ('Geachte mevrouw', 'Geachte mevrouw'), ('Geachte heer/mevrouw', 'Geachte heer/mevrouw'), ('Beste', 'Beste')], default='', max_length=30),
        ),
    ]
