# Generated by Django 6.0.2 on 2026-03-20 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_add_geachte_heer_mevrouw_aanhef'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='assigned_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prospects', to='dashboard.responsetemplate'),
        ),
    ]
