# Generated by Django 6.0.2 on 2026-03-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_seed_bouwbedrijven_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamagent',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
