# Generated by Django 6.0.2 on 2026-03-21 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_teamagent_is_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanjob',
            name='job_type',
            field=models.CharField(choices=[('dependency', 'Dependency Monitor'), ('fiscal', 'Bedrijfsmonitor'), ('custom', 'Custom Team'), ('compliance', 'WWFT Compliance'), ('vacancy', 'Vacature Monitor')], default='dependency', max_length=15),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=300, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('company_name', models.CharField(db_index=True, max_length=300)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('category', models.CharField(blank=True, choices=[('financieel', 'Financieel administratie'), ('data_analyse', 'Data-analyse'), ('ict', 'ICT en netwerken'), ('', 'Overig')], default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('salary', models.CharField(blank=True, default='', max_length=200)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('source', models.CharField(choices=[('indeed', 'Indeed'), ('jooble', 'Jooble'), ('adzuna', 'Adzuna')], max_length=50)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='dashboard.prospect')),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
