# Generated by Django 6.0.2 on 2026-03-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_seed_vacancy_prospect_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('new', 'Nieuw'), ('not_contacted', 'Niet benaderd'), ('contacted', 'Benaderd'), ('interested', 'Geïnteresseerd'), ('not_interested', 'Geen interesse'), ('client', 'Klant')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Wachten'), ('running', 'Bezig...'), ('completed', 'Afgerond'), ('failed', 'Mislukt')], db_index=True, default='pending', max_length=10),
        ),
    ]
