# Generated by Django 6.0.2 on 2026-03-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_seed_jaarrekening_analyzer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='source',
            field=models.CharField(choices=[('jooble', 'Jooble'), ('adzuna', 'Adzuna'), ('careerjet', 'CareerJet')], max_length=50),
        ),
    ]
