# Generated by Django 6.0.2 on 2026-03-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_alter_vacancy_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanjob',
            name='job_type',
            field=models.CharField(choices=[('dependency', 'Dependency Monitor'), ('fiscal', 'Bedrijfsmonitor'), ('custom', 'Custom Team'), ('compliance', 'WWFT Compliance'), ('vacancy', 'Vacature Monitor'), ('samenstelopdracht', 'Samenstelopdracht NV COS 4410')], default='dependency', max_length=20),
        ),
    ]
