# Generated by Django 6.0.2 on 2026-03-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_alter_scanjob_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancySearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('sources_used', models.CharField(blank=True, default='', max_length=200)),
                ('results_count', models.IntegerField(default=0)),
                ('companies_found', models.IntegerField(default=0)),
                ('new_companies', models.IntegerField(default=0)),
                ('avg_relevance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Vacancy searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='relevance_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='category',
            field=models.CharField(blank=True, choices=[('financieel', 'Financieel administratie'), ('data_analyse', 'Data-analyse'), ('ict', 'ICT en netwerken'), ('zzp_admin', 'ZZP Administratie'), ('automatisering', 'Automatisering'), ('', 'Overig')], default='', max_length=50),
        ),
    ]
