# Generated by Django 6.0.2 on 2026-03-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_update_klant_zzp_template_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='quality_score',
            field=models.PositiveSmallIntegerField(default=5, help_text='Kwaliteitsscore 1-10 van reviewer-agent'),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='status',
            field=models.CharField(choices=[('draft', 'Concept'), ('published', 'Gepubliceerd'), ('archived', 'Gearchiveerd')], db_index=True, default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='source',
            field=models.CharField(choices=[('jooble', 'Jooble'), ('adzuna', 'Adzuna'), ('careerjet', 'CareerJet')], db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='blogarticle',
            constraint=models.CheckConstraint(condition=models.Q(('quality_score__gte', 1), ('quality_score__lte', 10)), name='quality_score_range'),
        ),
        migrations.AddConstraint(
            model_name='vacancy',
            constraint=models.CheckConstraint(condition=models.Q(('relevance_score__gte', 0), ('relevance_score__lte', 100)), name='relevance_score_range'),
        ),
    ]
