# Generated by Django 6.0.2 on 2026-03-22 14:27

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='RJHoofdstuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('titel', models.CharField(max_length=300)),
                ('afdeling', models.CharField(choices=[('M', 'Microrechtspersonen'), ('A', 'Algemeen'), ('B', 'Jaarrekening'), ('C', 'Bijzondere kleine rechtspersonen'), ('D', 'Bijlagen')], max_length=1)),
                ('beschrijving', models.TextField(blank=True, default='')),
                ('editie', models.CharField(default='2022', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RJ Hoofdstuk',
                'verbose_name_plural': 'RJ Hoofdstukken',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RJRubriekMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubriek_naam', models.CharField(max_length=200, unique=True)),
                ('rubriek_code', models.CharField(blank=True, default='', max_length=20)),
                ('beschrijving', models.TextField(blank=True, default='')),
                ('hoofdstukken', models.ManyToManyField(related_name='rubrieken', to='dashboard.rjhoofdstuk')),
            ],
            options={
                'verbose_name': 'RJ Rubriek Mapping',
                'verbose_name_plural': 'RJ Rubriek Mappings',
                'ordering': ['rubriek_naam'],
            },
        ),
        migrations.CreateModel(
            name='RJSectie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraaf', models.CharField(max_length=20)),
                ('titel', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hoofdstuk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secties', to='dashboard.rjhoofdstuk')),
            ],
            options={
                'verbose_name': 'RJ Sectie',
                'verbose_name_plural': 'RJ Secties',
                'ordering': ['order'],
                'unique_together': {('hoofdstuk', 'paragraaf')},
            },
        ),
        migrations.CreateModel(
            name='RJAlinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=10)),
                ('sub_onderwerp', models.CharField(blank=True, default='', max_length=200)),
                ('inhoud', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sectie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alineas', to='dashboard.rjsectie')),
            ],
            options={
                'verbose_name': 'RJ Alinea',
                'verbose_name_plural': "RJ Alinea's",
                'ordering': ['order'],
                'unique_together': {('sectie', 'nummer')},
            },
        ),
    ]
