# Generated by Django 6.0.2 on 2026-03-22 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_add_accountant_to_rj_toets'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_order', models.PositiveIntegerField()),
                ('agent_name', models.CharField(max_length=200)),
                ('task_description', models.TextField(blank=True, default='')),
                ('output', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_outputs', to='dashboard.scanjob')),
            ],
            options={
                'ordering': ['task_order'],
            },
        ),
    ]
