# Generated by Django 6.0.2 on 2026-03-23 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_fix_manager_model_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rjalinea',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rjsectie',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teamvariable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='prospectgroup',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospect_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finding',
            name='category',
            field=models.CharField(choices=[('security', 'Security Vulnerability'), ('api_deprecation', 'API Deprecation'), ('breaking_change', 'Breaking Change'), ('outdated', 'Verouderd Package')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.CharField(choices=[('critical', 'Kritiek'), ('warning', 'Waarschuwing'), ('info', 'Informatie')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='finished_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='blogarticle',
            index=models.Index(fields=['status', '-created_at'], name='dashboard_b_status_62a9c5_idx'),
        ),
        migrations.AddIndex(
            model_name='prospect',
            index=models.Index(fields=['status', '-created_at'], name='dashboard_p_status_013095_idx'),
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['status', '-created_at'], name='dashboard_s_status_dd8e3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='rjalinea',
            constraint=models.UniqueConstraint(fields=('sectie', 'nummer'), name='unique_rj_alinea_nummer'),
        ),
        migrations.AddConstraint(
            model_name='rjsectie',
            constraint=models.UniqueConstraint(fields=('hoofdstuk', 'paragraaf'), name='unique_rj_sectie_paragraaf'),
        ),
        migrations.AddConstraint(
            model_name='teamvariable',
            constraint=models.UniqueConstraint(fields=('team', 'name'), name='unique_team_variable_name'),
        ),
    ]
