# Generated by Django 6.0.2 on 2026-03-23 18:17
# Data migration: assign existing Team and ProspectGroup records to the first superuser.

from django.db import migrations


def assign_ownership(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Team = apps.get_model("dashboard", "Team")
    ProspectGroup = apps.get_model("dashboard", "ProspectGroup")

    owner = User.objects.filter(is_superuser=True).order_by("pk").first()
    if not owner:
        owner = User.objects.order_by("pk").first()
    if not owner:
        return  # No users yet — nothing to assign

    Team.objects.filter(owner__isnull=True).update(owner=owner)
    ProspectGroup.objects.filter(owner__isnull=True).update(owner=owner)


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0076_alter_rjalinea_unique_together_and_more"),
    ]

    operations = [
        migrations.RunPython(assign_ownership, migrations.RunPython.noop),
    ]
