# Generated by Django 6.0.2 on 2026-03-24 13:41

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0077_assign_ownership_to_existing'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscaalArtikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=20)),
                ('titel', models.CharField(blank=True, default='', max_length=300)),
                ('volledige_tekst', models.TextField(blank=True, default='')),
                ('is_vervallen', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fiscaal Artikel',
                'verbose_name_plural': 'Fiscale Artikelen',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FiscaalHoofdstuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=20)),
                ('titel', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fiscaal Hoofdstuk',
                'verbose_name_plural': 'Fiscale Hoofdstukken',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FiscaleWet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('naam', models.CharField(max_length=300)),
                ('afkorting', models.CharField(max_length=50)),
                ('bwb_id', models.CharField(blank=True, default='', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fiscale Wet',
                'verbose_name_plural': 'Fiscale Wetten',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VpbBoekHoofdstuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=10, unique=True)),
                ('titel', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VPB Boek Hoofdstuk',
                'verbose_name_plural': 'VPB Boek Hoofdstukken',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FiscaalConceptMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_naam', models.CharField(max_length=200, unique=True)),
                ('trefwoorden', models.TextField(blank=True, default='')),
                ('beschrijving', models.TextField(blank=True, default='')),
                ('artikelen', models.ManyToManyField(related_name='concepten', to='dashboard.fiscaalartikel')),
            ],
            options={
                'verbose_name': 'Fiscaal Concept Mapping',
                'verbose_name_plural': 'Fiscale Concept Mappings',
                'ordering': ['concept_naam'],
            },
        ),
        migrations.AddField(
            model_name='fiscaalartikel',
            name='hoofdstuk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artikelen', to='dashboard.fiscaalhoofdstuk'),
        ),
        migrations.CreateModel(
            name='FiscaalLid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=10)),
                ('inhoud', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leden', to='dashboard.fiscaalartikel')),
            ],
            options={
                'verbose_name': 'Fiscaal Lid',
                'verbose_name_plural': 'Fiscale Leden',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='fiscaalhoofdstuk',
            name='wet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoofdstukken', to='dashboard.fiscalewet'),
        ),
        migrations.CreateModel(
            name='VpbBoekSectie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraaf', models.CharField(max_length=20)),
                ('titel', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hoofdstuk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secties', to='dashboard.vpbboekhoofdstuk')),
            ],
            options={
                'verbose_name': 'VPB Boek Sectie',
                'verbose_name_plural': 'VPB Boek Secties',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VpbBoekPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volgnummer', models.PositiveIntegerField()),
                ('inhoud', models.TextField()),
                ('pagina_start', models.PositiveIntegerField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sectie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='dashboard.vpbboeksectie')),
            ],
            options={
                'verbose_name': 'VPB Boek Passage',
                'verbose_name_plural': 'VPB Boek Passages',
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='fiscaalartikel',
            constraint=models.UniqueConstraint(fields=('hoofdstuk', 'nummer'), name='unique_fiscaal_artikel'),
        ),
        migrations.AddConstraint(
            model_name='fiscaallid',
            constraint=models.UniqueConstraint(fields=('artikel', 'nummer'), name='unique_fiscaal_lid'),
        ),
        migrations.AddConstraint(
            model_name='fiscaalhoofdstuk',
            constraint=models.UniqueConstraint(fields=('wet', 'nummer'), name='unique_fiscaal_hoofdstuk'),
        ),
        migrations.AddConstraint(
            model_name='vpbboeksectie',
            constraint=models.UniqueConstraint(fields=('hoofdstuk', 'paragraaf'), name='unique_vpbboek_sectie'),
        ),
        migrations.AddConstraint(
            model_name='vpbboekpassage',
            constraint=models.UniqueConstraint(fields=('sectie', 'volgnummer'), name='unique_vpbboek_passage'),
        ),
    ]
