# Generated by Django 6.0.2 on 2026-03-25 10:48

from django.db import migrations, models


SELECT_UPDATES = {
    "memo-standpunten-analyzer": {
        "domein": {
            "options": [
                {"value": "vpb", "label": "VPB \u2014 Vennootschapsbelasting", "tools": ["vpb_lookup", "vpb_boek_lookup", "vpb_tarieven"]},
                {"value": "ib", "label": "IB \u2014 Inkomstenbelasting", "tools": ["ib_lookup", "ib_tarieven"]},
            ],
        },
        "analyse_richting": {
            "options": [
                {"value": "alle", "label": "Alle invalshoeken"},
                {"value": "verdediging", "label": "Verdediging \u2014 versterk het standpunt"},
                {"value": "aanval_en_verdediging", "label": "Aanval & verdediging \u2014 zwakke plekken + tegenargumenten"},
                {"value": "fiscaal_advies", "label": "Fiscaal advies \u2014 gemiste kansen en risico\u2019s"},
            ],
        },
        "output_formaat": {
            "options": [
                {"value": "review", "label": "Review \u2014 gestructureerde analyse per onderwerp"},
                {"value": "herschreven_memo", "label": "Herschreven memo \u2014 memo met verwerkte analyses"},
                {"value": "brief_belastingdienst", "label": "Brief Belastingdienst \u2014 formele brief ter verdediging"},
                {"value": "alle", "label": "Alle formaten genereren"},
            ],
        },
    },
}


def convert_to_select(apps, schema_editor):
    TeamVariable = apps.get_model("dashboard", "TeamVariable")
    Team = apps.get_model("dashboard", "Team")
    for team_slug, variables in SELECT_UPDATES.items():
        team = Team.objects.filter(slug=team_slug).first()
        if not team:
            continue
        for var_name, config in variables.items():
            var = TeamVariable.objects.filter(team=team, name=var_name).first()
            if var:
                var.input_type = "select"
                var.options = config["options"]
                var.save()


def revert_to_text(apps, schema_editor):
    TeamVariable = apps.get_model("dashboard", "TeamVariable")
    Team = apps.get_model("dashboard", "Team")
    for team_slug, variables in SELECT_UPDATES.items():
        team = Team.objects.filter(slug=team_slug).first()
        if not team:
            continue
        for var_name in variables:
            var = TeamVariable.objects.filter(team=team, name=var_name).first()
            if var:
                var.input_type = "text"
                var.options = []
                var.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0080_seed_memo_standpunten_analyzer'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamvariable',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='Keuze-opties voor select type: [{value, label, tools?}]'),
        ),
        migrations.AlterField(
            model_name='teamvariable',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('file_path', 'File path'), ('select', 'Select')], default='text', max_length=10),
        ),
        migrations.RunPython(convert_to_select, revert_to_text),
    ]
