# Generated by Django 6.0.2 on 2026-03-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_teamvariable_options_and_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalewet',
            name='versie_datum',
            field=models.CharField(db_index=True, default='2024-01-01', help_text="Geldigheids-datum, bijv. '2025-01-01'", max_length=10),
        ),
        migrations.AddField(
            model_name='vpbboekhoofdstuk',
            name='editie',
            field=models.CharField(db_index=True, default='2023', help_text="Editie/boekjaar, bijv. '2023' voor 18e druk", max_length=10),
        ),
        migrations.AlterField(
            model_name='fiscalewet',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vpbboekhoofdstuk',
            name='nummer',
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name='fiscalewet',
            constraint=models.UniqueConstraint(fields=('code', 'versie_datum'), name='unique_wet_code_versie'),
        ),
        migrations.AddConstraint(
            model_name='vpbboekhoofdstuk',
            constraint=models.UniqueConstraint(fields=('nummer', 'editie'), name='unique_boek_nummer_editie'),
        ),
    ]
