# Generated by Django 6.0.2 on 2026-03-18 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=200)),
                ('smtp_port', models.IntegerField(default=465)),
                ('smtp_user', models.EmailField(help_text='Afzender e-mailadres', max_length=254)),
                ('smtp_password', models.CharField(help_text='App-wachtwoord', max_length=200)),
                ('display_name', models.CharField(blank=True, default='', help_text='Weergavenaam in From header', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'E-mail instellingen',
                'verbose_name_plural': 'E-mail instellingen',
            },
        ),
    ]
