# Generated by Django 6.0.2 on 2026-03-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='graph_client_id',
            field=models.CharField(blank=True, default='', help_text='Azure AD Client ID', max_length=100),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='graph_client_secret',
            field=models.CharField(blank=True, default='', help_text='Azure AD Client Secret', max_length=200),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='graph_tenant_id',
            field=models.CharField(blank=True, default='', help_text='Azure AD Tenant ID', max_length=100),
        ),
    ]
