# Generated by Django 6.0.2 on 2026-03-19 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_graph_api_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsettings',
            name='smtp_host',
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='smtp_password',
        ),
        migrations.RemoveField(
            model_name='emailsettings',
            name='smtp_port',
        ),
    ]
