# Generated by Django 6.0.2 on 2026-03-21 21:52

import accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_emailsettings_smtp_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='graph_client_secret',
            field=accounts.fields.EncryptedCharField(blank=True, default='', help_text='Azure AD Client Secret (versleuteld opgeslagen)', max_length=500),
        ),
    ]
