# Generated by Django 6.0.2 on 2026-03-21 21:52

from django.db import migrations


def encrypt_existing_secrets(apps, schema_editor):
    """Re-save existing EmailSettings so the EncryptedCharField encrypts plaintext values."""
    EmailSettings = apps.get_model("accounts", "EmailSettings")
    for es in EmailSettings.objects.exclude(graph_client_secret=""):
        # Trigger get_prep_value by saving — the field encrypts on write
        es.save(update_fields=["graph_client_secret"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_encrypt_graph_client_secret"),
    ]

    operations = [
        migrations.RunPython(encrypt_existing_secrets, migrations.RunPython.noop),
    ]
