# Generated by Django 6.0.2 on 2026-03-21 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0051_alter_scanjob_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_key', models.CharField(choices=[('randvoorwaarden', 'Randvoorwaarden'), ('aanvaarding', 'Aanvaarding en continuering'), ('inzicht', 'Inzicht'), ('samenstellen', 'Samenstellen'), ('nalezen', 'Nalezen'), ('verklaring', 'Samenstellingsverklaring')], max_length=30, unique=True)),
                ('naam', models.CharField(max_length=100)),
                ('beschrijving', models.TextField(blank=True, default='')),
                ('doelen', models.TextField(blank=True, default='')),
                ('randvoorwaarden', models.TextField(blank=True, default='')),
                ('referenties', models.TextField(blank=True, default='')),
                ('run_nummer', models.IntegerField(choices=[(1, 'Run 1 — Analyse'), (2, 'Run 2 — Afsluiting')], default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samenstellen_fasen', to='dashboard.team')),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': 'Fasen',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Opdracht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_naam', models.CharField(max_length=200)),
                ('boekjaar', models.CharField(default='2025', max_length=10)),
                ('rechtsvorm', models.CharField(default='BV', max_length=50)),
                ('sector', models.CharField(blank=True, default='', max_length=200)),
                ('verslaggevingsstelsel', models.CharField(default='RJ', max_length=50)),
                ('concept_pdf', models.CharField(blank=True, default='', max_length=500)),
                ('definitieve_pdf', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('nieuw', 'Nieuw'), ('run1_bezig', 'Analyse bezig'), ('run1_klaar', 'Analyse afgerond'), ('run2_bezig', 'Nalezen bezig'), ('afgerond', 'Afgerond')], db_index=True, default='nieuw', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run1_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.scanjob')),
                ('run2_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.scanjob')),
            ],
            options={
                'verbose_name': 'Samenstelopdracht',
                'verbose_name_plural': 'Samenstelopdrachten',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=300)),
                ('bestand', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('fase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='samenstellen.fase')),
                ('opdracht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenten', to='samenstellen.opdracht')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documenten',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FaseResultaat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Wachten'), ('running', 'Bezig'), ('completed', 'Afgerond'), ('failed', 'Mislukt')], default='pending', max_length=10)),
                ('resultaat', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('token_count', models.IntegerField(default=0)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samenstellen.fase')),
                ('opdracht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fase_resultaten', to='samenstellen.opdracht')),
            ],
            options={
                'verbose_name': 'Fase-resultaat',
                'verbose_name_plural': 'Fase-resultaten',
                'ordering': ['fase__order'],
                'unique_together': {('opdracht', 'fase')},
            },
        ),
    ]
